# Generated by Django 3.1.2 on 2022-07-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220720_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='model',
            new_name='productType',
        ),
    ]
