# Generated by Django 3.1.2 on 2022-07-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
    ]
