# Generated by Django 3.1.2 on 2022-07-18 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_remove_cart_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
